
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.28.3/share/cmake/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 24.0.0 - x86_64
...
